[workspace]

members = [
    "applied-crypto-references",
    "applied-crypto-references/merlin-transcripts",
    "applied-crypto-references/zksnarks",
    "applied-crypto-references/curve-operations",
    "proving-libraries"
]
