[package]
name = "proving-libraries"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bulletproofs = "4.0.0"
curve25519-dalek-ng = "4.1.1"
lazy_static = "1.4.0"
merlin = "3.0.0"
rand = "0.8.3"