[package]
name = "curve-operations"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bls12_381 = {version = "0.7.0", features = ["groups"] }
curve25519-dalek = "3.2.0"
lazy_static = "1.4.0"