[package]
name = "applied-crypto-examples"
authors = ["Michael Turner"]
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tutorial"
path = "src/bin/tutorial.rs"

[dependencies]
clap = { version = "3.2.19", features = ["derive"] }
merlin-example = { path = "merlin-transcripts" }
