[package]
name = "applied-crypto-examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tutorial"
path = "src/bin/tutorial.rs"

[dependencies]
clap = { version = "3.2.19", features = ["derive"] }
curve25519-dalek = "4.0.0-pre.2"
hex = "0.4.3"
merlin = "3.0.0"
