[package]
name = "zksnarks-example"
authors = ["Michael Turner"]
version = "0.1.0"
edition = "2021"

[dependencies]
bls12_381 = {version = "0.7.0", features = ["groups"] }
ff = "0.12.1"
hex = "0.4.3"
rand = "0.8.5"